POST https://retoolapi.dev/iXFthB/data HTTP/1.1
Content-Type: : application/json

 {
    "id": 45,
    "title": "Big test 2",
    "director": "Kalin",
    "imdb_votes": 8342,
    "distributor": "MGMsdf",
    "imdb_rating": 9
  }

###