POST https://retoolapi.dev/iXFthB/data
accept: application/json
content-Type: application/json

{
    "id": 45,
    "title": "Kalin test 1",
    "director": "Kalin",
    "imdb_votes": "3343",
    "distributor": "MGMsdf",
    "imdb_rating": "2.5"
 }
###
POST https://retoolapi.dev/iXFthB/data
accept: application/json
content-Type: application/json

{
    "id": 46,
    "title": "Kalin test 2",
    "director": "Kalin",
    "imdb_votes": "3343",
    "distributor": "MGMsdf",
    "imdb_rating": "2.5"
 }
###
PUT  https://retoolapi.dev/iXFthB/data/47
accept: application/json
content-Type: application/json

{
    "id": 47,
    "title":"Kalin patch 123",
    "director":"Ivan Nikolov",
    "imdb_votes": "2453",
    "distributor": "Boqna",
    "imdb_rating": "1.7"
 }
###